alias manage="uv run manage.py"
alias runserver="uv run manage.py runserver"
alias makemigrations="uv run manage.py makemigrations"
alias collectstatic="uv run manage.py collectstatic"
alias sphinx-watch="uv run watchmedo shell-command --patterns='*.rst;*.py;docs/_static/*.css' --drop --wait --recursive --command='uv run --group docs sphinx-build -M html docs docs/build --nitpicky --verbose --write-all' ."
alias sphinx-build="uv run --group docs sphinx-build --nitpicky --verbose --write-all -b html docs docs/build"